### ISSUE TITLE
lacking cljc support

### ISSUE THREAD

**Issue by JvJ** [typedclojure/typed-clojure-mode#10]
I'm writing some typed cljc, and when type checking, I get the following error:

Type Error (NO_SOURCE_FILE:nil:nil)
Internal Error (:<NO LINE>) Cannot find file: guymover/game_state.clj

**Comment by frenchy64** [comment]
Can I assume you actually have a file `guymover/game_state.cljc`? Does this also fail at the REPL? Which version of core.typed?

**Comment by JvJ** [comment]
Sorry, I forgot to mention I fixed it by upgrading the core.typed version.

**Comment by frenchy64** [comment]
Great!
